services:
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: eventsauce-php
        volumes:
            - .:/app:cached
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
            - ~/.composer:/root/.composer:delegated
        working_dir: /app
        tty: true
